manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
#new stuff start
#    - name: zmk
#      remote: zmkfirmware
#      revision: feat/pointers-move-scroll
#      import: app/west.yml
#    - name: zmk-pmw3610-driver
#      remote: inorichi
#      revision: main
#new stuff end
  self:
    path: config
